// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TestingModule.Data;

namespace TestingModule.Migrations
{
    [DbContext(typeof(TestsContext))]
    [Migration("20180530202107_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestingModule.Models.Duty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("RubricId");

                    b.HasKey("ID");

                    b.HasIndex("RubricId");

                    b.ToTable("Duty");
                });

            modelBuilder.Entity("TestingModule.Models.Rubric", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SubjectId");

                    b.HasKey("ID");

                    b.HasIndex("SubjectId");

                    b.ToTable("Rubric");
                });

            modelBuilder.Entity("TestingModule.Models.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("TestingModule.Models.UnitTest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arguments");

                    b.Property<int>("DutyId");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.HasIndex("DutyId");

                    b.ToTable("UnitTest");
                });

            modelBuilder.Entity("TestingModule.Models.Duty", b =>
                {
                    b.HasOne("TestingModule.Models.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestingModule.Models.Rubric", b =>
                {
                    b.HasOne("TestingModule.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestingModule.Models.UnitTest", b =>
                {
                    b.HasOne("TestingModule.Models.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
